/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author demys
 */
public class FrameForca extends javax.swing.JFrame {

    int erros = 0;
    char errou;
    String palavras[] = {"Homem-Aranha", "Shang-Chi", "Homem-Formiga",
        "Pantera Negra",
        "Quasar",
        "Ciclope",
        "Fera",
        "Mancha Solar",
        "Vampira",
        "Colossus",
        "Gambit",
        "Tempestade",
        "Solaris",
        "Banshee",
        "Psylocke",
        "Jubileu",
        "Anjo",
        "Cable",
        "Domino",
        "Mercurio",
        "Luke Cage",
        "Mulher-Aranha",
        "Falcao",
        "Namor",
        "Tocha Humana",
        "Motoqueiro Fantasma",
        "Elektra",
        "Surfista Prateado",
        "Hulk",
        "Visao",
        "Thor",
        "Homem de Ferro",
        "Capitao America",
        "Blade",
        "Demolidor"}, palavra, forca = "", letra, letraJogador, palavraArray[], palavraJogador = "";

    Random rn = new Random();

    //Gerar uma nova palavra e imprimir os traços
    public void iniciarForca() {
        lblInfo.setVisible(false);
        lblLetras.setText("");
        lblDesenho.setIcon(new ImageIcon(getClass().getResource("forca.png")));
        palavra = palavras[rn.nextInt(palavras.length)].toUpperCase();
        System.out.println(palavra);
        txtLetra.setEnabled(true);
        btnJogar.setText("JOGAR");
        txtLetra.requestFocus();
        errou = 's';
        erros = 0;
        palavraArray = new String[palavra.length()];
        forca = "";

        //Imprimir a forca com os tracinhos pela primeira vez
        for (int i = 0; i < palavra.length(); i++) {
            letra = palavra.substring(i, i + 1);
            if (!(letra.equals("-") || letra.equals(" "))) {
                palavraArray[i] = "*";
                forca += "_" + " ";
            } else {
                palavraArray[i] = letra;
                forca += letra + " ";
            }
        }
        lblForca.setText(forca);
        forca = "";
    }

    //Apagando uma segunda letra digitada e convertendo a letra em maiúsculo
    public void apagarLetra() {
        if (txtLetra.getText().length() > 0) {
            char letra = txtLetra.getText().charAt(0);
            txtLetra.setText((letra + "").toUpperCase());
        }
    }

    public FrameForca() {
        initComponents();
        iniciarForca();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblDesenho = new javax.swing.JLabel();
        txtLetra = new javax.swing.JTextField();
        lblInfo = new javax.swing.JLabel();
        btnJogar = new javax.swing.JButton();
        lblForca = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblLetras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forca Marvel - Descubra o nome de um herói da Marvel");
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setName(""); // NOI18N

        lblDesenho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/forca.png"))); // NOI18N

        txtLetra.setBackground(new java.awt.Color(204, 255, 204));
        txtLetra.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtLetra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLetra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLetraKeyReleased(evt);
            }
        });

        lblInfo.setBackground(new java.awt.Color(204, 255, 204));
        lblInfo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(255, 51, 51));
        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo.setText("------");

        btnJogar.setBackground(new java.awt.Color(153, 204, 255));
        btnJogar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnJogar.setForeground(new java.awt.Color(102, 0, 255));
        btnJogar.setText("JOGAR");
        btnJogar.setActionCommand("");
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });

        lblForca.setBackground(new java.awt.Color(204, 255, 204));
        lblForca.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblForca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForca.setText("------");

        jLabel1.setText("Letras erradas:");

        lblLetras.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblLetras.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblForca, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblDesenho, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLetra)
                            .addComponent(btnJogar, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(lblLetras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDesenho, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblForca, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        // TODO add your handling code here:
        lblInfo.setVisible(false);
        if (erros >= 6 || btnJogar.getText().equalsIgnoreCase("NOVO JOGO")) {
            iniciarForca();
        } else {
            if (txtLetra.getText().equals("")) {
                lblInfo.setVisible(true);
                lblInfo.setText("Digite uma letra!");
                txtLetra.requestFocus();
            } else {
                forca = "";

                for (int i = 0; i < palavra.length(); i++) {
                    //Acertou letra
                    if (txtLetra.getText().equalsIgnoreCase(palavra.substring(i, i + 1))) {
                        palavraArray[i] = txtLetra.getText();
                        errou = 'n';
                    }
                }

                for (int i = 0; i < palavra.length(); i++) {
                    if (palavraArray[i].equalsIgnoreCase("*")) {
                        forca += "_" + " ";
                    } else {
                        forca += palavraArray[i] + " ";
                    }
                }
                lblForca.setText(forca);
                forca = "";
                

                if (errou == 's') {
                    erros++;
                    if(!lblLetras.getText().contains(txtLetra.getText())) {
                        lblLetras.setVisible(true);
                        lblLetras.setText(lblLetras.getText() + txtLetra.getText() + " ");
                    }
                    switch (erros) {
                        case 1:
                            lblDesenho.setIcon(new ImageIcon(getClass().getResource("01.png")));
                            break;
                        case 2:
                            lblDesenho.setIcon(new ImageIcon(getClass().getResource("02.png")));
                            break;
                        case 3:
                            lblDesenho.setIcon(new ImageIcon(getClass().getResource("03.png")));
                            break;
                        case 4:
                            lblDesenho.setIcon(new ImageIcon(getClass().getResource("04.png")));
                            break;
                        case 5:
                            lblDesenho.setIcon(new ImageIcon(getClass().getResource("05.png")));
                            break;
                        default:
                            lblDesenho.setIcon(new ImageIcon(getClass().getResource("06.png")));
                            break;
                    }
                }
                
                txtLetra.setText("");
                txtLetra.requestFocus();
                
                errou = 's';

                if (erros == 6) {
                    lblInfo.setVisible(true);
                    lblInfo.setText("VOCÊ PERDEU!!");
                    txtLetra.setEnabled(false);
                    btnJogar.setText("NOVO JOGO");
                }
            }

        }
        palavraJogador = "";
        for (int i = 0; i < palavraArray.length; i++) {
            palavraJogador += palavraArray[i];
        }
        System.out.println("Palavra jogador: " + palavraJogador);
        System.out.println("Palavra: " + palavra);
        if (palavraJogador.equals(palavra)) {
            lblInfo.setVisible(true);
            lblInfo.setText("VOCÊ VENCEU!!");
            txtLetra.setEnabled(false);
            btnJogar.setText("NOVO JOGO");
        }
    }//GEN-LAST:event_btnJogarActionPerformed

    private void txtLetraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLetraKeyReleased
        // TODO add your handling code here:
        apagarLetra();
    }//GEN-LAST:event_txtLetraKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameForca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDesenho;
    private javax.swing.JLabel lblForca;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblLetras;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField txtLetra;
    // End of variables declaration//GEN-END:variables
}
